A = int(input())
B = int(input())
C = int(input())

num = str(A * B * C)

print(num.count('0'))
print(num.count('1'))
print(num.count('2'))
print(num.count('3'))
print(num.count('4'))
print(num.count('5'))
print(num.count('6'))
print(num.count('7'))
print(num.count('8'))
print(num.count('9'))
