SELECT A.ANIMAL_ID, A.NAME
FROM (SELECT B.ANIMAL_ID, B.NAME
     FROM ANIMAL_INS A INNER JOIN ANIMAL_OUTS B
     ON A.ANIMAL_ID = B.ANIMAL_ID
     ORDER BY TRUNC(B.DATETIME) - TRUNC(A.DATETIME) DESC) A
WHERE ROWNUM <= 2