SELECT B.HISTORY_ID, MIN(A.DAILY_FEE*(B.END_DATE-B.START_DATE+1)*NVL(DISCOUNT_RATE,1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID = B.CAR_ID
LEFT OUTER JOIN (
    SELECT CAR_TYPE, DURATION_TYPE, 1-(DISCOUNT_RATE/100) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
) C
ON A.CAR_TYPE = C.CAR_TYPE
    AND (B.END_DATE-B.START_DATE+1) >= TO_NUMBER(REGEXP_REPLACE(C.DURATION_TYPE,'[^0-9]'))
WHERE A.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC